import axios from "axios";

const baseDomain = "https://newcheck.pasaledai.com";

export const customHeaders = {
  "Content-Type": "application/json",
  Accept: "application/json",
  Authorization:
    "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTg1MzczM2JkOGZhOGQ4YTg4NzY4MTRlNTAxZjFjYjA1OTc5ZGY0MzdmODJjNDQyNzE4ODE5MDQwYTEzZjRiZDk3YmZjOGRmNTA0NTczYmQiLCJpYXQiOjE3MzI2MDQ4NzUuNzYxNDQ0LCJuYmYiOjE3MzI2MDQ4NzUuNzYxNDQ3LCJleHAiOjE3NjQxNDA4NzUuNzUwNTU1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.zgSBQkX5FDOA-Fj-P9Z-HKIMKOO2aKUMcxpfEo-fNZY9PRe_RnmReLro_STb9pwQ2Z_Voi-sbngJNL2WuXZoM2K_x93xUweG7QeDY4cENeH5J5XL4pQRrAvrd2tyZLuNyE58kPAoG-899Y1CXX8Fgr5Kqg0Rg4nL101fEWIChpjcAFkU8aLCKJzf9aa_Ax1kbbiFr5WUMDLBb8wnlbJP5Zkh9RBZpQq3iapSklTd-R8LEur-8GzOFsww1WTe8dW-O1IXFUWl7etaW60TO9vzINjFhuAkl3c8kziR4PLDHj3xSWQNfINLwYAyfs_Pk0xr2rEKyXd9uNqc7AGsqMRQKlBw8ZXF_6HR3G5PWg_udeKyEjWMr9Q8DAs0A5EnG9V8gKJoCmtjYNqGLjf8BJTjnxqYFAJ0mEVNbinPQMuZkSfrNtZd4l9ezLrIEMP_FWzOyLb0qlBHGfsJhBuTZzIm1z4r1zR7npkYcw9TazBG7hL9EFSOZSO1YUscJgvJpjbMoup2czfltNbiUAERliodo422IIgYikhKVfsE-4xaJ7ncXitYDWKkENvJDcjAoIZ-Q3G0JoSmRdMv20Ip3T_axHVWA--WGZ94cqUBorUAK8C_zr0McYO9cJhy5sCuGhznBW6UVnZBTgTbfypxEgmmihJr0JghKb5z56kNgXNLgnA",
};

export const baseUrl = `${baseDomain}`;

export default axios.create({
  baseUrl,
  headers: customHeaders,
});
